/********************************************************************************
** Form generated from reading UI file 'gameWithoutChatWithAlice.ui'
**
** Created by: Qt User Interface Compiler version 5.12.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_GAMEWITHOUTCHATWITHALICE_H
#define UI_GAMEWITHOUTCHATWITHALICE_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFormLayout>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_GameWithoutChatWithAlice
{
public:
    QGraphicsView *boardView;
    QLabel *imageLabel;
    QWidget *formLayoutWidget_3;
    QFormLayout *formLayout_3;
    QLabel *takenLabel;
    QLabel *chgTakenLabel;
    QWidget *verticalLayoutWidget;
    QVBoxLayout *verticalLayout_2;
    QFormLayout *formLayout_4;
    QLabel *modeLabel;
    QLabel *chgModelabel;
    QLabel *colourLabel;
    QLabel *chgColourLabel;
    QLabel *lastMoveLabel;
    QLabel *chgLastMovelabel;
    QLabel *opponentNameLabel;
    QLabel *chgOpponentNamelabel;
    QPushButton *surrendButton;
    QWidget *verticalLayoutWidget_2;
    QVBoxLayout *verticalLayout_3;
    QFormLayout *formLayout_2;
    QLabel *timeLabel;
    QLabel *chgTimeLabel;
    QLabel *checkUpdatelabel;
    QLabel *turnLabel;
    QWidget *formLayoutWidget_5;
    QFormLayout *formLayout_5;
    QLabel *takenEnnemyLabel;
    QLabel *chgTakenEnnemyLabel;
    QGraphicsView *boardView2;
    QPushButton *h3PushButton;
    QPushButton *e4PushButton;
    QPushButton *b5PushButton;
    QPushButton *e1PushButton;
    QPushButton *c3PushButton;
    QPushButton *b3PushButton;
    QPushButton *d7PushButton;
    QPushButton *f7PushButton;
    QPushButton *h7PushButton;
    QPushButton *d4PushButton;
    QPushButton *e5PushButton;
    QPushButton *e8PushButton;
    QPushButton *g8PushButton;
    QPushButton *b7PushButton;
    QPushButton *a4PushButton;
    QPushButton *g4PushButton;
    QPushButton *a1PushButton;
    QPushButton *a6PushButton;
    QPushButton *g7PushButton;
    QPushButton *c7PushButton;
    QPushButton *h8PushButton;
    QPushButton *g5PushButton;
    QPushButton *b4PushButton;
    QPushButton *f6PushButton;
    QPushButton *g2PushButton;
    QPushButton *g1PushButton;
    QPushButton *h4PushButton;
    QPushButton *d3PushButton;
    QPushButton *a3PushButton;
    QPushButton *a7PushButton;
    QPushButton *h1PushButton;
    QPushButton *h6PushButton;
    QPushButton *f2PushButton;
    QPushButton *d6PushButton;
    QPushButton *f1PushButton;
    QPushButton *f4PushButton;
    QPushButton *e6PushButton;
    QPushButton *d5PushButton;
    QPushButton *a8PushButton;
    QPushButton *c1PushButton;
    QPushButton *g3PushButton;
    QPushButton *d2PushButton;
    QPushButton *d8PushButton;
    QGraphicsView *graphicsView;
    QPushButton *f5PushButton;
    QPushButton *f8PushButton;
    QPushButton *g6PushButton;
    QPushButton *f3PushButton;
    QPushButton *e3PushButton;
    QPushButton *b6PushButton;
    QPushButton *c8PushButton;
    QPushButton *e2PushButton;
    QPushButton *h2PushButton;
    QPushButton *h5PushButton;
    QPushButton *a2PushButton;
    QPushButton *b8PushButton;
    QPushButton *c4PushButton;
    QPushButton *c5PushButton;
    QPushButton *b2PushButton;
    QPushButton *c2PushButton;
    QPushButton *c6PushButton;
    QPushButton *e7PushButton;
    QPushButton *d1PushButton;
    QPushButton *b1PushButton;
    QPushButton *a5PushButton;
    QPushButton *b5PushButton_2;
    QPushButton *b6PushButton_2;
    QPushButton *a4PushButton_2;
    QPushButton *a6PushButton_2;
    QPushButton *a8PushButton_2;
    QPushButton *b4PushButton_2;
    QPushButton *b8PushButton_2;
    QPushButton *b2PushButton_2;
    QPushButton *b7PushButton_2;
    QPushButton *a2PushButton_2;
    QPushButton *a5PushButton_2;
    QPushButton *a3PushButton_2;
    QPushButton *a7PushButton_2;
    QPushButton *a1PushButton_2;
    QPushButton *b1PushButton_2;
    QPushButton *b3PushButton_2;
    QPushButton *f1PushButton_2;
    QPushButton *d8PushButton_2;
    QPushButton *f3PushButton_2;
    QPushButton *f7PushButton_2;
    QPushButton *c8PushButton_2;
    QPushButton *f5PushButton_2;
    QPushButton *c7PushButton_2;
    QPushButton *f4PushButton_2;
    QPushButton *c3PushButton_2;
    QPushButton *d7PushButton_2;
    QPushButton *e7PushButton_2;
    QPushButton *c5PushButton_2;
    QPushButton *f6PushButton_2;
    QPushButton *d2PushButton_2;
    QPushButton *e2PushButton_2;
    QPushButton *e5PushButton_2;
    QPushButton *f8PushButton_2;
    QPushButton *e1PushButton_2;
    QPushButton *e3PushButton_2;
    QPushButton *e8PushButton_2;
    QPushButton *d6PushButton_2;
    QPushButton *c1PushButton_2;
    QPushButton *c4PushButton_2;
    QPushButton *d1PushButton_2;
    QPushButton *d5PushButton_2;
    QPushButton *d4PushButton_2;
    QPushButton *f2PushButton_2;
    QPushButton *c6PushButton_2;
    QPushButton *d3PushButton_2;
    QPushButton *e4PushButton_2;
    QPushButton *e6PushButton_2;
    QPushButton *c2PushButton_2;
    QPushButton *g3PushButton_2;
    QPushButton *g7PushButton_2;
    QPushButton *g1PushButton_2;
    QPushButton *g2PushButton_2;
    QPushButton *g5PushButton_2;
    QPushButton *g6PushButton_2;
    QPushButton *g4PushButton_2;
    QPushButton *g8PushButton_2;
    QPushButton *h5PushButton_2;
    QPushButton *h1PushButton_2;
    QPushButton *h7PushButton_2;
    QPushButton *h3PushButton_2;
    QPushButton *h6PushButton_2;
    QPushButton *h8PushButton_2;
    QPushButton *h2PushButton_2;
    QPushButton *h4PushButton_2;

    void setupUi(QDialog *GameWithoutChatWithAlice)
    {
        if (GameWithoutChatWithAlice->objectName().isEmpty())
            GameWithoutChatWithAlice->setObjectName(QString::fromUtf8("GameWithoutChatWithAlice"));
        GameWithoutChatWithAlice->resize(1200, 600);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(GameWithoutChatWithAlice->sizePolicy().hasHeightForWidth());
        GameWithoutChatWithAlice->setSizePolicy(sizePolicy);
        GameWithoutChatWithAlice->setMinimumSize(QSize(1200, 600));
        GameWithoutChatWithAlice->setMaximumSize(QSize(1200, 800));
        boardView = new QGraphicsView(GameWithoutChatWithAlice);
        boardView->setObjectName(QString::fromUtf8("boardView"));
        boardView->setGeometry(QRect(250, 100, 400, 400));
        sizePolicy.setHeightForWidth(boardView->sizePolicy().hasHeightForWidth());
        boardView->setSizePolicy(sizePolicy);
        imageLabel = new QLabel(GameWithoutChatWithAlice);
        imageLabel->setObjectName(QString::fromUtf8("imageLabel"));
        imageLabel->setGeometry(QRect(20, 440, 221, 141));
        imageLabel->setPixmap(QPixmap(QString::fromUtf8(":/catmeme.jpg")));
        imageLabel->setScaledContents(true);
        formLayoutWidget_3 = new QWidget(GameWithoutChatWithAlice);
        formLayoutWidget_3->setObjectName(QString::fromUtf8("formLayoutWidget_3"));
        formLayoutWidget_3->setGeometry(QRect(250, 530, 401, 61));
        formLayout_3 = new QFormLayout(formLayoutWidget_3);
        formLayout_3->setObjectName(QString::fromUtf8("formLayout_3"));
        formLayout_3->setContentsMargins(0, 0, 0, 0);
        takenLabel = new QLabel(formLayoutWidget_3);
        takenLabel->setObjectName(QString::fromUtf8("takenLabel"));

        formLayout_3->setWidget(0, QFormLayout::LabelRole, takenLabel);

        chgTakenLabel = new QLabel(formLayoutWidget_3);
        chgTakenLabel->setObjectName(QString::fromUtf8("chgTakenLabel"));

        formLayout_3->setWidget(0, QFormLayout::FieldRole, chgTakenLabel);

        verticalLayoutWidget = new QWidget(GameWithoutChatWithAlice);
        verticalLayoutWidget->setObjectName(QString::fromUtf8("verticalLayoutWidget"));
        verticalLayoutWidget->setGeometry(QRect(20, 20, 221, 401));
        verticalLayout_2 = new QVBoxLayout(verticalLayoutWidget);
        verticalLayout_2->setObjectName(QString::fromUtf8("verticalLayout_2"));
        verticalLayout_2->setContentsMargins(0, 0, 0, 0);
        formLayout_4 = new QFormLayout();
        formLayout_4->setObjectName(QString::fromUtf8("formLayout_4"));
        formLayout_4->setHorizontalSpacing(20);
        formLayout_4->setVerticalSpacing(20);
        formLayout_4->setContentsMargins(-1, 20, -1, 20);
        modeLabel = new QLabel(verticalLayoutWidget);
        modeLabel->setObjectName(QString::fromUtf8("modeLabel"));

        formLayout_4->setWidget(0, QFormLayout::LabelRole, modeLabel);

        chgModelabel = new QLabel(verticalLayoutWidget);
        chgModelabel->setObjectName(QString::fromUtf8("chgModelabel"));

        formLayout_4->setWidget(0, QFormLayout::FieldRole, chgModelabel);

        colourLabel = new QLabel(verticalLayoutWidget);
        colourLabel->setObjectName(QString::fromUtf8("colourLabel"));

        formLayout_4->setWidget(1, QFormLayout::LabelRole, colourLabel);

        chgColourLabel = new QLabel(verticalLayoutWidget);
        chgColourLabel->setObjectName(QString::fromUtf8("chgColourLabel"));

        formLayout_4->setWidget(1, QFormLayout::FieldRole, chgColourLabel);

        lastMoveLabel = new QLabel(verticalLayoutWidget);
        lastMoveLabel->setObjectName(QString::fromUtf8("lastMoveLabel"));

        formLayout_4->setWidget(2, QFormLayout::LabelRole, lastMoveLabel);

        chgLastMovelabel = new QLabel(verticalLayoutWidget);
        chgLastMovelabel->setObjectName(QString::fromUtf8("chgLastMovelabel"));

        formLayout_4->setWidget(2, QFormLayout::FieldRole, chgLastMovelabel);

        opponentNameLabel = new QLabel(verticalLayoutWidget);
        opponentNameLabel->setObjectName(QString::fromUtf8("opponentNameLabel"));

        formLayout_4->setWidget(3, QFormLayout::LabelRole, opponentNameLabel);

        chgOpponentNamelabel = new QLabel(verticalLayoutWidget);
        chgOpponentNamelabel->setObjectName(QString::fromUtf8("chgOpponentNamelabel"));

        formLayout_4->setWidget(3, QFormLayout::FieldRole, chgOpponentNamelabel);


        verticalLayout_2->addLayout(formLayout_4);

        surrendButton = new QPushButton(verticalLayoutWidget);
        surrendButton->setObjectName(QString::fromUtf8("surrendButton"));

        verticalLayout_2->addWidget(surrendButton);

        verticalLayoutWidget_2 = new QWidget(GameWithoutChatWithAlice);
        verticalLayoutWidget_2->setObjectName(QString::fromUtf8("verticalLayoutWidget_2"));
        verticalLayoutWidget_2->setGeometry(QRect(1060, 20, 131, 481));
        verticalLayout_3 = new QVBoxLayout(verticalLayoutWidget_2);
        verticalLayout_3->setObjectName(QString::fromUtf8("verticalLayout_3"));
        verticalLayout_3->setContentsMargins(0, 0, 0, 0);
        formLayout_2 = new QFormLayout();
        formLayout_2->setObjectName(QString::fromUtf8("formLayout_2"));
        formLayout_2->setHorizontalSpacing(20);
        formLayout_2->setVerticalSpacing(20);
        formLayout_2->setContentsMargins(-1, 20, -1, 20);
        timeLabel = new QLabel(verticalLayoutWidget_2);
        timeLabel->setObjectName(QString::fromUtf8("timeLabel"));

        formLayout_2->setWidget(0, QFormLayout::LabelRole, timeLabel);

        chgTimeLabel = new QLabel(verticalLayoutWidget_2);
        chgTimeLabel->setObjectName(QString::fromUtf8("chgTimeLabel"));

        formLayout_2->setWidget(0, QFormLayout::FieldRole, chgTimeLabel);

        checkUpdatelabel = new QLabel(verticalLayoutWidget_2);
        checkUpdatelabel->setObjectName(QString::fromUtf8("checkUpdatelabel"));

        formLayout_2->setWidget(1, QFormLayout::LabelRole, checkUpdatelabel);

        turnLabel = new QLabel(verticalLayoutWidget_2);
        turnLabel->setObjectName(QString::fromUtf8("turnLabel"));

        formLayout_2->setWidget(1, QFormLayout::FieldRole, turnLabel);


        verticalLayout_3->addLayout(formLayout_2);

        formLayoutWidget_5 = new QWidget(GameWithoutChatWithAlice);
        formLayoutWidget_5->setObjectName(QString::fromUtf8("formLayoutWidget_5"));
        formLayoutWidget_5->setGeometry(QRect(250, 30, 401, 61));
        formLayout_5 = new QFormLayout(formLayoutWidget_5);
        formLayout_5->setObjectName(QString::fromUtf8("formLayout_5"));
        formLayout_5->setContentsMargins(0, 0, 0, 0);
        takenEnnemyLabel = new QLabel(formLayoutWidget_5);
        takenEnnemyLabel->setObjectName(QString::fromUtf8("takenEnnemyLabel"));

        formLayout_5->setWidget(0, QFormLayout::LabelRole, takenEnnemyLabel);

        chgTakenEnnemyLabel = new QLabel(formLayoutWidget_5);
        chgTakenEnnemyLabel->setObjectName(QString::fromUtf8("chgTakenEnnemyLabel"));

        formLayout_5->setWidget(0, QFormLayout::FieldRole, chgTakenEnnemyLabel);

        boardView2 = new QGraphicsView(GameWithoutChatWithAlice);
        boardView2->setObjectName(QString::fromUtf8("boardView2"));
        boardView2->setGeometry(QRect(660, 100, 400, 400));
        sizePolicy.setHeightForWidth(boardView2->sizePolicy().hasHeightForWidth());
        boardView2->setSizePolicy(sizePolicy);
        h3PushButton = new QPushButton(GameWithoutChatWithAlice);
        h3PushButton->setObjectName(QString::fromUtf8("h3PushButton"));
        h3PushButton->setGeometry(QRect(600, 350, 50, 50));
        h3PushButton->setMinimumSize(QSize(50, 50));
        h3PushButton->setMaximumSize(QSize(50, 50));
        h3PushButton->setStyleSheet(QString::fromUtf8(""));
        e4PushButton = new QPushButton(GameWithoutChatWithAlice);
        e4PushButton->setObjectName(QString::fromUtf8("e4PushButton"));
        e4PushButton->setGeometry(QRect(450, 300, 50, 50));
        e4PushButton->setMinimumSize(QSize(50, 50));
        e4PushButton->setMaximumSize(QSize(50, 50));
        e4PushButton->setStyleSheet(QString::fromUtf8(""));
        b5PushButton = new QPushButton(GameWithoutChatWithAlice);
        b5PushButton->setObjectName(QString::fromUtf8("b5PushButton"));
        b5PushButton->setGeometry(QRect(300, 250, 50, 50));
        b5PushButton->setMinimumSize(QSize(50, 50));
        b5PushButton->setMaximumSize(QSize(50, 50));
        b5PushButton->setStyleSheet(QString::fromUtf8(""));
        e1PushButton = new QPushButton(GameWithoutChatWithAlice);
        e1PushButton->setObjectName(QString::fromUtf8("e1PushButton"));
        e1PushButton->setGeometry(QRect(450, 450, 50, 50));
        e1PushButton->setMinimumSize(QSize(50, 50));
        e1PushButton->setMaximumSize(QSize(50, 50));
        e1PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        c3PushButton = new QPushButton(GameWithoutChatWithAlice);
        c3PushButton->setObjectName(QString::fromUtf8("c3PushButton"));
        c3PushButton->setGeometry(QRect(350, 350, 50, 50));
        c3PushButton->setMinimumSize(QSize(50, 50));
        c3PushButton->setMaximumSize(QSize(50, 50));
        c3PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        b3PushButton = new QPushButton(GameWithoutChatWithAlice);
        b3PushButton->setObjectName(QString::fromUtf8("b3PushButton"));
        b3PushButton->setGeometry(QRect(300, 350, 50, 50));
        b3PushButton->setMinimumSize(QSize(50, 50));
        b3PushButton->setMaximumSize(QSize(50, 50));
        b3PushButton->setStyleSheet(QString::fromUtf8(""));
        d7PushButton = new QPushButton(GameWithoutChatWithAlice);
        d7PushButton->setObjectName(QString::fromUtf8("d7PushButton"));
        d7PushButton->setGeometry(QRect(400, 150, 50, 50));
        d7PushButton->setMinimumSize(QSize(50, 50));
        d7PushButton->setMaximumSize(QSize(50, 50));
        d7PushButton->setStyleSheet(QString::fromUtf8(""));
        f7PushButton = new QPushButton(GameWithoutChatWithAlice);
        f7PushButton->setObjectName(QString::fromUtf8("f7PushButton"));
        f7PushButton->setGeometry(QRect(500, 150, 50, 50));
        f7PushButton->setMinimumSize(QSize(50, 50));
        f7PushButton->setMaximumSize(QSize(50, 50));
        f7PushButton->setStyleSheet(QString::fromUtf8(""));
        h7PushButton = new QPushButton(GameWithoutChatWithAlice);
        h7PushButton->setObjectName(QString::fromUtf8("h7PushButton"));
        h7PushButton->setGeometry(QRect(600, 150, 50, 50));
        h7PushButton->setMinimumSize(QSize(50, 50));
        h7PushButton->setMaximumSize(QSize(50, 50));
        h7PushButton->setStyleSheet(QString::fromUtf8(""));
        d4PushButton = new QPushButton(GameWithoutChatWithAlice);
        d4PushButton->setObjectName(QString::fromUtf8("d4PushButton"));
        d4PushButton->setGeometry(QRect(400, 300, 50, 50));
        d4PushButton->setMinimumSize(QSize(50, 50));
        d4PushButton->setMaximumSize(QSize(50, 50));
        d4PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        e5PushButton = new QPushButton(GameWithoutChatWithAlice);
        e5PushButton->setObjectName(QString::fromUtf8("e5PushButton"));
        e5PushButton->setGeometry(QRect(450, 250, 50, 50));
        e5PushButton->setMinimumSize(QSize(50, 50));
        e5PushButton->setMaximumSize(QSize(50, 50));
        e5PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        e8PushButton = new QPushButton(GameWithoutChatWithAlice);
        e8PushButton->setObjectName(QString::fromUtf8("e8PushButton"));
        e8PushButton->setGeometry(QRect(450, 100, 50, 50));
        e8PushButton->setMinimumSize(QSize(50, 50));
        e8PushButton->setMaximumSize(QSize(50, 50));
        e8PushButton->setStyleSheet(QString::fromUtf8(""));
        g8PushButton = new QPushButton(GameWithoutChatWithAlice);
        g8PushButton->setObjectName(QString::fromUtf8("g8PushButton"));
        g8PushButton->setGeometry(QRect(550, 100, 50, 50));
        g8PushButton->setMinimumSize(QSize(50, 50));
        g8PushButton->setMaximumSize(QSize(50, 50));
        g8PushButton->setStyleSheet(QString::fromUtf8(""));
        b7PushButton = new QPushButton(GameWithoutChatWithAlice);
        b7PushButton->setObjectName(QString::fromUtf8("b7PushButton"));
        b7PushButton->setGeometry(QRect(300, 150, 50, 50));
        b7PushButton->setMinimumSize(QSize(50, 50));
        b7PushButton->setMaximumSize(QSize(50, 50));
        b7PushButton->setStyleSheet(QString::fromUtf8(""));
        a4PushButton = new QPushButton(GameWithoutChatWithAlice);
        a4PushButton->setObjectName(QString::fromUtf8("a4PushButton"));
        a4PushButton->setGeometry(QRect(250, 300, 50, 50));
        a4PushButton->setMinimumSize(QSize(50, 50));
        a4PushButton->setMaximumSize(QSize(50, 50));
        a4PushButton->setStyleSheet(QString::fromUtf8(""));
        g4PushButton = new QPushButton(GameWithoutChatWithAlice);
        g4PushButton->setObjectName(QString::fromUtf8("g4PushButton"));
        g4PushButton->setGeometry(QRect(550, 300, 50, 50));
        g4PushButton->setMinimumSize(QSize(50, 50));
        g4PushButton->setMaximumSize(QSize(50, 50));
        g4PushButton->setStyleSheet(QString::fromUtf8(""));
        a1PushButton = new QPushButton(GameWithoutChatWithAlice);
        a1PushButton->setObjectName(QString::fromUtf8("a1PushButton"));
        a1PushButton->setGeometry(QRect(250, 450, 50, 50));
        a1PushButton->setMinimumSize(QSize(50, 50));
        a1PushButton->setMaximumSize(QSize(50, 50));
        a1PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        a6PushButton = new QPushButton(GameWithoutChatWithAlice);
        a6PushButton->setObjectName(QString::fromUtf8("a6PushButton"));
        a6PushButton->setGeometry(QRect(250, 200, 50, 50));
        a6PushButton->setMinimumSize(QSize(50, 50));
        a6PushButton->setMaximumSize(QSize(50, 50));
        a6PushButton->setStyleSheet(QString::fromUtf8(""));
        g7PushButton = new QPushButton(GameWithoutChatWithAlice);
        g7PushButton->setObjectName(QString::fromUtf8("g7PushButton"));
        g7PushButton->setGeometry(QRect(550, 150, 50, 50));
        g7PushButton->setMinimumSize(QSize(50, 50));
        g7PushButton->setMaximumSize(QSize(50, 50));
        g7PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        c7PushButton = new QPushButton(GameWithoutChatWithAlice);
        c7PushButton->setObjectName(QString::fromUtf8("c7PushButton"));
        c7PushButton->setGeometry(QRect(350, 150, 50, 50));
        c7PushButton->setMinimumSize(QSize(50, 50));
        c7PushButton->setMaximumSize(QSize(50, 50));
        c7PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        h8PushButton = new QPushButton(GameWithoutChatWithAlice);
        h8PushButton->setObjectName(QString::fromUtf8("h8PushButton"));
        h8PushButton->setGeometry(QRect(600, 100, 50, 50));
        h8PushButton->setMinimumSize(QSize(50, 50));
        h8PushButton->setMaximumSize(QSize(50, 50));
        h8PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        g5PushButton = new QPushButton(GameWithoutChatWithAlice);
        g5PushButton->setObjectName(QString::fromUtf8("g5PushButton"));
        g5PushButton->setGeometry(QRect(550, 250, 50, 50));
        g5PushButton->setMinimumSize(QSize(50, 50));
        g5PushButton->setMaximumSize(QSize(50, 50));
        g5PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        b4PushButton = new QPushButton(GameWithoutChatWithAlice);
        b4PushButton->setObjectName(QString::fromUtf8("b4PushButton"));
        b4PushButton->setGeometry(QRect(300, 300, 50, 50));
        b4PushButton->setMinimumSize(QSize(50, 50));
        b4PushButton->setMaximumSize(QSize(50, 50));
        b4PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        f6PushButton = new QPushButton(GameWithoutChatWithAlice);
        f6PushButton->setObjectName(QString::fromUtf8("f6PushButton"));
        f6PushButton->setGeometry(QRect(500, 200, 50, 50));
        f6PushButton->setMinimumSize(QSize(50, 50));
        f6PushButton->setMaximumSize(QSize(50, 50));
        f6PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        g2PushButton = new QPushButton(GameWithoutChatWithAlice);
        g2PushButton->setObjectName(QString::fromUtf8("g2PushButton"));
        g2PushButton->setGeometry(QRect(550, 400, 50, 50));
        g2PushButton->setMinimumSize(QSize(50, 50));
        g2PushButton->setMaximumSize(QSize(50, 50));
        g2PushButton->setStyleSheet(QString::fromUtf8(""));
        g1PushButton = new QPushButton(GameWithoutChatWithAlice);
        g1PushButton->setObjectName(QString::fromUtf8("g1PushButton"));
        g1PushButton->setGeometry(QRect(550, 450, 50, 50));
        g1PushButton->setMinimumSize(QSize(50, 50));
        g1PushButton->setMaximumSize(QSize(50, 50));
        g1PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        h4PushButton = new QPushButton(GameWithoutChatWithAlice);
        h4PushButton->setObjectName(QString::fromUtf8("h4PushButton"));
        h4PushButton->setGeometry(QRect(600, 300, 50, 50));
        h4PushButton->setMinimumSize(QSize(50, 50));
        h4PushButton->setMaximumSize(QSize(50, 50));
        h4PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        d3PushButton = new QPushButton(GameWithoutChatWithAlice);
        d3PushButton->setObjectName(QString::fromUtf8("d3PushButton"));
        d3PushButton->setGeometry(QRect(400, 350, 50, 50));
        d3PushButton->setMinimumSize(QSize(50, 50));
        d3PushButton->setMaximumSize(QSize(50, 50));
        d3PushButton->setStyleSheet(QString::fromUtf8(""));
        a3PushButton = new QPushButton(GameWithoutChatWithAlice);
        a3PushButton->setObjectName(QString::fromUtf8("a3PushButton"));
        a3PushButton->setGeometry(QRect(250, 350, 50, 50));
        a3PushButton->setMinimumSize(QSize(50, 50));
        a3PushButton->setMaximumSize(QSize(50, 50));
        a3PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        a7PushButton = new QPushButton(GameWithoutChatWithAlice);
        a7PushButton->setObjectName(QString::fromUtf8("a7PushButton"));
        a7PushButton->setGeometry(QRect(250, 150, 50, 50));
        a7PushButton->setMinimumSize(QSize(50, 50));
        a7PushButton->setMaximumSize(QSize(50, 50));
        a7PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        h1PushButton = new QPushButton(GameWithoutChatWithAlice);
        h1PushButton->setObjectName(QString::fromUtf8("h1PushButton"));
        h1PushButton->setGeometry(QRect(600, 450, 50, 50));
        h1PushButton->setMinimumSize(QSize(50, 50));
        h1PushButton->setMaximumSize(QSize(50, 50));
        h1PushButton->setStyleSheet(QString::fromUtf8(""));
        h6PushButton = new QPushButton(GameWithoutChatWithAlice);
        h6PushButton->setObjectName(QString::fromUtf8("h6PushButton"));
        h6PushButton->setGeometry(QRect(600, 200, 50, 50));
        h6PushButton->setMinimumSize(QSize(50, 50));
        h6PushButton->setMaximumSize(QSize(50, 50));
        h6PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        f2PushButton = new QPushButton(GameWithoutChatWithAlice);
        f2PushButton->setObjectName(QString::fromUtf8("f2PushButton"));
        f2PushButton->setGeometry(QRect(500, 400, 50, 50));
        f2PushButton->setMinimumSize(QSize(50, 50));
        f2PushButton->setMaximumSize(QSize(50, 50));
        f2PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        d6PushButton = new QPushButton(GameWithoutChatWithAlice);
        d6PushButton->setObjectName(QString::fromUtf8("d6PushButton"));
        d6PushButton->setGeometry(QRect(400, 200, 50, 50));
        d6PushButton->setMinimumSize(QSize(50, 50));
        d6PushButton->setMaximumSize(QSize(50, 50));
        d6PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        f1PushButton = new QPushButton(GameWithoutChatWithAlice);
        f1PushButton->setObjectName(QString::fromUtf8("f1PushButton"));
        f1PushButton->setGeometry(QRect(500, 450, 50, 50));
        f1PushButton->setMinimumSize(QSize(50, 50));
        f1PushButton->setMaximumSize(QSize(50, 50));
        f1PushButton->setStyleSheet(QString::fromUtf8(""));
        f4PushButton = new QPushButton(GameWithoutChatWithAlice);
        f4PushButton->setObjectName(QString::fromUtf8("f4PushButton"));
        f4PushButton->setGeometry(QRect(500, 300, 50, 50));
        f4PushButton->setMinimumSize(QSize(50, 50));
        f4PushButton->setMaximumSize(QSize(50, 50));
        f4PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        e6PushButton = new QPushButton(GameWithoutChatWithAlice);
        e6PushButton->setObjectName(QString::fromUtf8("e6PushButton"));
        e6PushButton->setGeometry(QRect(450, 200, 50, 50));
        e6PushButton->setMinimumSize(QSize(50, 50));
        e6PushButton->setMaximumSize(QSize(50, 50));
        e6PushButton->setStyleSheet(QString::fromUtf8(""));
        d5PushButton = new QPushButton(GameWithoutChatWithAlice);
        d5PushButton->setObjectName(QString::fromUtf8("d5PushButton"));
        d5PushButton->setGeometry(QRect(400, 250, 50, 50));
        d5PushButton->setMinimumSize(QSize(50, 50));
        d5PushButton->setMaximumSize(QSize(50, 50));
        d5PushButton->setStyleSheet(QString::fromUtf8(""));
        a8PushButton = new QPushButton(GameWithoutChatWithAlice);
        a8PushButton->setObjectName(QString::fromUtf8("a8PushButton"));
        a8PushButton->setGeometry(QRect(250, 100, 50, 50));
        a8PushButton->setMinimumSize(QSize(50, 50));
        a8PushButton->setMaximumSize(QSize(50, 50));
        a8PushButton->setStyleSheet(QString::fromUtf8(""));
        c1PushButton = new QPushButton(GameWithoutChatWithAlice);
        c1PushButton->setObjectName(QString::fromUtf8("c1PushButton"));
        c1PushButton->setGeometry(QRect(350, 450, 50, 50));
        c1PushButton->setMinimumSize(QSize(50, 50));
        c1PushButton->setMaximumSize(QSize(50, 50));
        c1PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        g3PushButton = new QPushButton(GameWithoutChatWithAlice);
        g3PushButton->setObjectName(QString::fromUtf8("g3PushButton"));
        g3PushButton->setGeometry(QRect(550, 350, 50, 50));
        g3PushButton->setMinimumSize(QSize(50, 50));
        g3PushButton->setMaximumSize(QSize(50, 50));
        g3PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        d2PushButton = new QPushButton(GameWithoutChatWithAlice);
        d2PushButton->setObjectName(QString::fromUtf8("d2PushButton"));
        d2PushButton->setGeometry(QRect(400, 400, 50, 50));
        d2PushButton->setMinimumSize(QSize(50, 50));
        d2PushButton->setMaximumSize(QSize(50, 50));
        d2PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        d8PushButton = new QPushButton(GameWithoutChatWithAlice);
        d8PushButton->setObjectName(QString::fromUtf8("d8PushButton"));
        d8PushButton->setGeometry(QRect(400, 100, 50, 50));
        d8PushButton->setMinimumSize(QSize(50, 50));
        d8PushButton->setMaximumSize(QSize(50, 50));
        d8PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        graphicsView = new QGraphicsView(GameWithoutChatWithAlice);
        graphicsView->setObjectName(QString::fromUtf8("graphicsView"));
        graphicsView->setGeometry(QRect(250, 100, 400, 400));
        sizePolicy.setHeightForWidth(graphicsView->sizePolicy().hasHeightForWidth());
        graphicsView->setSizePolicy(sizePolicy);
        f5PushButton = new QPushButton(GameWithoutChatWithAlice);
        f5PushButton->setObjectName(QString::fromUtf8("f5PushButton"));
        f5PushButton->setGeometry(QRect(500, 250, 50, 50));
        f5PushButton->setMinimumSize(QSize(50, 50));
        f5PushButton->setMaximumSize(QSize(50, 50));
        f5PushButton->setStyleSheet(QString::fromUtf8(""));
        f8PushButton = new QPushButton(GameWithoutChatWithAlice);
        f8PushButton->setObjectName(QString::fromUtf8("f8PushButton"));
        f8PushButton->setGeometry(QRect(500, 100, 50, 50));
        f8PushButton->setMinimumSize(QSize(50, 50));
        f8PushButton->setMaximumSize(QSize(50, 50));
        f8PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        g6PushButton = new QPushButton(GameWithoutChatWithAlice);
        g6PushButton->setObjectName(QString::fromUtf8("g6PushButton"));
        g6PushButton->setGeometry(QRect(550, 200, 50, 50));
        g6PushButton->setMinimumSize(QSize(50, 50));
        g6PushButton->setMaximumSize(QSize(50, 50));
        g6PushButton->setStyleSheet(QString::fromUtf8(""));
        f3PushButton = new QPushButton(GameWithoutChatWithAlice);
        f3PushButton->setObjectName(QString::fromUtf8("f3PushButton"));
        f3PushButton->setGeometry(QRect(500, 350, 50, 50));
        f3PushButton->setMinimumSize(QSize(50, 50));
        f3PushButton->setMaximumSize(QSize(50, 50));
        f3PushButton->setStyleSheet(QString::fromUtf8(""));
        e3PushButton = new QPushButton(GameWithoutChatWithAlice);
        e3PushButton->setObjectName(QString::fromUtf8("e3PushButton"));
        e3PushButton->setGeometry(QRect(450, 350, 50, 50));
        e3PushButton->setMinimumSize(QSize(50, 50));
        e3PushButton->setMaximumSize(QSize(50, 50));
        e3PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        b6PushButton = new QPushButton(GameWithoutChatWithAlice);
        b6PushButton->setObjectName(QString::fromUtf8("b6PushButton"));
        b6PushButton->setGeometry(QRect(300, 200, 50, 50));
        b6PushButton->setMinimumSize(QSize(50, 50));
        b6PushButton->setMaximumSize(QSize(50, 50));
        b6PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        c8PushButton = new QPushButton(GameWithoutChatWithAlice);
        c8PushButton->setObjectName(QString::fromUtf8("c8PushButton"));
        c8PushButton->setGeometry(QRect(350, 100, 50, 50));
        c8PushButton->setMinimumSize(QSize(50, 50));
        c8PushButton->setMaximumSize(QSize(50, 50));
        c8PushButton->setStyleSheet(QString::fromUtf8(""));
        e2PushButton = new QPushButton(GameWithoutChatWithAlice);
        e2PushButton->setObjectName(QString::fromUtf8("e2PushButton"));
        e2PushButton->setGeometry(QRect(450, 400, 50, 50));
        e2PushButton->setMinimumSize(QSize(50, 50));
        e2PushButton->setMaximumSize(QSize(50, 50));
        e2PushButton->setStyleSheet(QString::fromUtf8(""));
        h2PushButton = new QPushButton(GameWithoutChatWithAlice);
        h2PushButton->setObjectName(QString::fromUtf8("h2PushButton"));
        h2PushButton->setGeometry(QRect(600, 400, 50, 50));
        h2PushButton->setMinimumSize(QSize(50, 50));
        h2PushButton->setMaximumSize(QSize(50, 50));
        h2PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        h5PushButton = new QPushButton(GameWithoutChatWithAlice);
        h5PushButton->setObjectName(QString::fromUtf8("h5PushButton"));
        h5PushButton->setGeometry(QRect(600, 250, 50, 50));
        h5PushButton->setMinimumSize(QSize(50, 50));
        h5PushButton->setMaximumSize(QSize(50, 50));
        h5PushButton->setStyleSheet(QString::fromUtf8(""));
        a2PushButton = new QPushButton(GameWithoutChatWithAlice);
        a2PushButton->setObjectName(QString::fromUtf8("a2PushButton"));
        a2PushButton->setGeometry(QRect(250, 400, 50, 50));
        a2PushButton->setMinimumSize(QSize(50, 50));
        a2PushButton->setMaximumSize(QSize(50, 50));
        a2PushButton->setStyleSheet(QString::fromUtf8(""));
        b8PushButton = new QPushButton(GameWithoutChatWithAlice);
        b8PushButton->setObjectName(QString::fromUtf8("b8PushButton"));
        b8PushButton->setGeometry(QRect(300, 100, 50, 50));
        b8PushButton->setMinimumSize(QSize(50, 50));
        b8PushButton->setMaximumSize(QSize(50, 50));
        b8PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        c4PushButton = new QPushButton(GameWithoutChatWithAlice);
        c4PushButton->setObjectName(QString::fromUtf8("c4PushButton"));
        c4PushButton->setGeometry(QRect(350, 300, 50, 50));
        c4PushButton->setMinimumSize(QSize(50, 50));
        c4PushButton->setMaximumSize(QSize(50, 50));
        c4PushButton->setStyleSheet(QString::fromUtf8(""));
        c5PushButton = new QPushButton(GameWithoutChatWithAlice);
        c5PushButton->setObjectName(QString::fromUtf8("c5PushButton"));
        c5PushButton->setGeometry(QRect(350, 250, 50, 50));
        c5PushButton->setMinimumSize(QSize(50, 50));
        c5PushButton->setMaximumSize(QSize(50, 50));
        c5PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        b2PushButton = new QPushButton(GameWithoutChatWithAlice);
        b2PushButton->setObjectName(QString::fromUtf8("b2PushButton"));
        b2PushButton->setGeometry(QRect(300, 400, 50, 50));
        b2PushButton->setMinimumSize(QSize(50, 50));
        b2PushButton->setMaximumSize(QSize(50, 50));
        b2PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        c2PushButton = new QPushButton(GameWithoutChatWithAlice);
        c2PushButton->setObjectName(QString::fromUtf8("c2PushButton"));
        c2PushButton->setGeometry(QRect(350, 400, 50, 50));
        c2PushButton->setMinimumSize(QSize(50, 50));
        c2PushButton->setMaximumSize(QSize(50, 50));
        c2PushButton->setStyleSheet(QString::fromUtf8(""));
        c6PushButton = new QPushButton(GameWithoutChatWithAlice);
        c6PushButton->setObjectName(QString::fromUtf8("c6PushButton"));
        c6PushButton->setGeometry(QRect(350, 200, 50, 50));
        c6PushButton->setMinimumSize(QSize(50, 50));
        c6PushButton->setMaximumSize(QSize(50, 50));
        c6PushButton->setStyleSheet(QString::fromUtf8(""));
        e7PushButton = new QPushButton(GameWithoutChatWithAlice);
        e7PushButton->setObjectName(QString::fromUtf8("e7PushButton"));
        e7PushButton->setGeometry(QRect(450, 150, 50, 50));
        e7PushButton->setMinimumSize(QSize(50, 50));
        e7PushButton->setMaximumSize(QSize(50, 50));
        e7PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        d1PushButton = new QPushButton(GameWithoutChatWithAlice);
        d1PushButton->setObjectName(QString::fromUtf8("d1PushButton"));
        d1PushButton->setGeometry(QRect(400, 450, 50, 50));
        d1PushButton->setMinimumSize(QSize(50, 50));
        d1PushButton->setMaximumSize(QSize(50, 50));
        d1PushButton->setStyleSheet(QString::fromUtf8(""));
        b1PushButton = new QPushButton(GameWithoutChatWithAlice);
        b1PushButton->setObjectName(QString::fromUtf8("b1PushButton"));
        b1PushButton->setGeometry(QRect(300, 450, 50, 50));
        b1PushButton->setMinimumSize(QSize(50, 50));
        b1PushButton->setMaximumSize(QSize(50, 50));
        b1PushButton->setStyleSheet(QString::fromUtf8(""));
        a5PushButton = new QPushButton(GameWithoutChatWithAlice);
        a5PushButton->setObjectName(QString::fromUtf8("a5PushButton"));
        a5PushButton->setGeometry(QRect(250, 250, 50, 50));
        a5PushButton->setMinimumSize(QSize(50, 50));
        a5PushButton->setMaximumSize(QSize(50, 50));
        a5PushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        b5PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        b5PushButton_2->setObjectName(QString::fromUtf8("b5PushButton_2"));
        b5PushButton_2->setGeometry(QRect(710, 250, 50, 50));
        b5PushButton_2->setMinimumSize(QSize(50, 50));
        b5PushButton_2->setMaximumSize(QSize(50, 50));
        b5PushButton_2->setStyleSheet(QString::fromUtf8(""));
        b6PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        b6PushButton_2->setObjectName(QString::fromUtf8("b6PushButton_2"));
        b6PushButton_2->setGeometry(QRect(710, 200, 50, 50));
        b6PushButton_2->setMinimumSize(QSize(50, 50));
        b6PushButton_2->setMaximumSize(QSize(50, 50));
        b6PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        a4PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        a4PushButton_2->setObjectName(QString::fromUtf8("a4PushButton_2"));
        a4PushButton_2->setGeometry(QRect(660, 300, 50, 50));
        a4PushButton_2->setMinimumSize(QSize(50, 50));
        a4PushButton_2->setMaximumSize(QSize(50, 50));
        a4PushButton_2->setStyleSheet(QString::fromUtf8(""));
        a6PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        a6PushButton_2->setObjectName(QString::fromUtf8("a6PushButton_2"));
        a6PushButton_2->setGeometry(QRect(660, 200, 50, 50));
        a6PushButton_2->setMinimumSize(QSize(50, 50));
        a6PushButton_2->setMaximumSize(QSize(50, 50));
        a6PushButton_2->setStyleSheet(QString::fromUtf8(""));
        a8PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        a8PushButton_2->setObjectName(QString::fromUtf8("a8PushButton_2"));
        a8PushButton_2->setGeometry(QRect(660, 100, 50, 50));
        a8PushButton_2->setMinimumSize(QSize(50, 50));
        a8PushButton_2->setMaximumSize(QSize(50, 50));
        a8PushButton_2->setStyleSheet(QString::fromUtf8(""));
        b4PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        b4PushButton_2->setObjectName(QString::fromUtf8("b4PushButton_2"));
        b4PushButton_2->setGeometry(QRect(710, 300, 50, 50));
        b4PushButton_2->setMinimumSize(QSize(50, 50));
        b4PushButton_2->setMaximumSize(QSize(50, 50));
        b4PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        b8PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        b8PushButton_2->setObjectName(QString::fromUtf8("b8PushButton_2"));
        b8PushButton_2->setGeometry(QRect(710, 100, 50, 50));
        b8PushButton_2->setMinimumSize(QSize(50, 50));
        b8PushButton_2->setMaximumSize(QSize(50, 50));
        b8PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        b2PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        b2PushButton_2->setObjectName(QString::fromUtf8("b2PushButton_2"));
        b2PushButton_2->setGeometry(QRect(710, 400, 50, 50));
        b2PushButton_2->setMinimumSize(QSize(50, 50));
        b2PushButton_2->setMaximumSize(QSize(50, 50));
        b2PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        b7PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        b7PushButton_2->setObjectName(QString::fromUtf8("b7PushButton_2"));
        b7PushButton_2->setGeometry(QRect(710, 150, 50, 50));
        b7PushButton_2->setMinimumSize(QSize(50, 50));
        b7PushButton_2->setMaximumSize(QSize(50, 50));
        b7PushButton_2->setStyleSheet(QString::fromUtf8(""));
        a2PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        a2PushButton_2->setObjectName(QString::fromUtf8("a2PushButton_2"));
        a2PushButton_2->setGeometry(QRect(660, 400, 50, 50));
        a2PushButton_2->setMinimumSize(QSize(50, 50));
        a2PushButton_2->setMaximumSize(QSize(50, 50));
        a2PushButton_2->setStyleSheet(QString::fromUtf8(""));
        a5PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        a5PushButton_2->setObjectName(QString::fromUtf8("a5PushButton_2"));
        a5PushButton_2->setGeometry(QRect(660, 250, 50, 50));
        a5PushButton_2->setMinimumSize(QSize(50, 50));
        a5PushButton_2->setMaximumSize(QSize(50, 50));
        a5PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        a3PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        a3PushButton_2->setObjectName(QString::fromUtf8("a3PushButton_2"));
        a3PushButton_2->setGeometry(QRect(660, 350, 50, 50));
        a3PushButton_2->setMinimumSize(QSize(50, 50));
        a3PushButton_2->setMaximumSize(QSize(50, 50));
        a3PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        a7PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        a7PushButton_2->setObjectName(QString::fromUtf8("a7PushButton_2"));
        a7PushButton_2->setGeometry(QRect(660, 150, 50, 50));
        a7PushButton_2->setMinimumSize(QSize(50, 50));
        a7PushButton_2->setMaximumSize(QSize(50, 50));
        a7PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        a1PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        a1PushButton_2->setObjectName(QString::fromUtf8("a1PushButton_2"));
        a1PushButton_2->setGeometry(QRect(660, 450, 50, 50));
        a1PushButton_2->setMinimumSize(QSize(50, 50));
        a1PushButton_2->setMaximumSize(QSize(50, 50));
        a1PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        b1PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        b1PushButton_2->setObjectName(QString::fromUtf8("b1PushButton_2"));
        b1PushButton_2->setGeometry(QRect(710, 450, 50, 50));
        b1PushButton_2->setMinimumSize(QSize(50, 50));
        b1PushButton_2->setMaximumSize(QSize(50, 50));
        b1PushButton_2->setStyleSheet(QString::fromUtf8(""));
        b3PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        b3PushButton_2->setObjectName(QString::fromUtf8("b3PushButton_2"));
        b3PushButton_2->setGeometry(QRect(710, 350, 50, 50));
        b3PushButton_2->setMinimumSize(QSize(50, 50));
        b3PushButton_2->setMaximumSize(QSize(50, 50));
        b3PushButton_2->setStyleSheet(QString::fromUtf8(""));
        f1PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        f1PushButton_2->setObjectName(QString::fromUtf8("f1PushButton_2"));
        f1PushButton_2->setGeometry(QRect(910, 450, 50, 50));
        f1PushButton_2->setMinimumSize(QSize(50, 50));
        f1PushButton_2->setMaximumSize(QSize(50, 50));
        f1PushButton_2->setStyleSheet(QString::fromUtf8(""));
        d8PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        d8PushButton_2->setObjectName(QString::fromUtf8("d8PushButton_2"));
        d8PushButton_2->setGeometry(QRect(810, 100, 50, 50));
        d8PushButton_2->setMinimumSize(QSize(50, 50));
        d8PushButton_2->setMaximumSize(QSize(50, 50));
        d8PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        f3PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        f3PushButton_2->setObjectName(QString::fromUtf8("f3PushButton_2"));
        f3PushButton_2->setGeometry(QRect(910, 350, 50, 50));
        f3PushButton_2->setMinimumSize(QSize(50, 50));
        f3PushButton_2->setMaximumSize(QSize(50, 50));
        f3PushButton_2->setStyleSheet(QString::fromUtf8(""));
        f7PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        f7PushButton_2->setObjectName(QString::fromUtf8("f7PushButton_2"));
        f7PushButton_2->setGeometry(QRect(910, 150, 50, 50));
        f7PushButton_2->setMinimumSize(QSize(50, 50));
        f7PushButton_2->setMaximumSize(QSize(50, 50));
        f7PushButton_2->setStyleSheet(QString::fromUtf8(""));
        c8PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        c8PushButton_2->setObjectName(QString::fromUtf8("c8PushButton_2"));
        c8PushButton_2->setGeometry(QRect(760, 100, 50, 50));
        c8PushButton_2->setMinimumSize(QSize(50, 50));
        c8PushButton_2->setMaximumSize(QSize(50, 50));
        c8PushButton_2->setStyleSheet(QString::fromUtf8(""));
        f5PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        f5PushButton_2->setObjectName(QString::fromUtf8("f5PushButton_2"));
        f5PushButton_2->setGeometry(QRect(910, 250, 50, 50));
        f5PushButton_2->setMinimumSize(QSize(50, 50));
        f5PushButton_2->setMaximumSize(QSize(50, 50));
        f5PushButton_2->setStyleSheet(QString::fromUtf8(""));
        c7PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        c7PushButton_2->setObjectName(QString::fromUtf8("c7PushButton_2"));
        c7PushButton_2->setGeometry(QRect(760, 150, 50, 50));
        c7PushButton_2->setMinimumSize(QSize(50, 50));
        c7PushButton_2->setMaximumSize(QSize(50, 50));
        c7PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        f4PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        f4PushButton_2->setObjectName(QString::fromUtf8("f4PushButton_2"));
        f4PushButton_2->setGeometry(QRect(910, 300, 50, 50));
        f4PushButton_2->setMinimumSize(QSize(50, 50));
        f4PushButton_2->setMaximumSize(QSize(50, 50));
        f4PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        c3PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        c3PushButton_2->setObjectName(QString::fromUtf8("c3PushButton_2"));
        c3PushButton_2->setGeometry(QRect(760, 350, 50, 50));
        c3PushButton_2->setMinimumSize(QSize(50, 50));
        c3PushButton_2->setMaximumSize(QSize(50, 50));
        c3PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        d7PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        d7PushButton_2->setObjectName(QString::fromUtf8("d7PushButton_2"));
        d7PushButton_2->setGeometry(QRect(810, 150, 50, 50));
        d7PushButton_2->setMinimumSize(QSize(50, 50));
        d7PushButton_2->setMaximumSize(QSize(50, 50));
        d7PushButton_2->setStyleSheet(QString::fromUtf8(""));
        e7PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        e7PushButton_2->setObjectName(QString::fromUtf8("e7PushButton_2"));
        e7PushButton_2->setGeometry(QRect(860, 150, 50, 50));
        e7PushButton_2->setMinimumSize(QSize(50, 50));
        e7PushButton_2->setMaximumSize(QSize(50, 50));
        e7PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        c5PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        c5PushButton_2->setObjectName(QString::fromUtf8("c5PushButton_2"));
        c5PushButton_2->setGeometry(QRect(760, 250, 50, 50));
        c5PushButton_2->setMinimumSize(QSize(50, 50));
        c5PushButton_2->setMaximumSize(QSize(50, 50));
        c5PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        f6PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        f6PushButton_2->setObjectName(QString::fromUtf8("f6PushButton_2"));
        f6PushButton_2->setGeometry(QRect(910, 200, 50, 50));
        f6PushButton_2->setMinimumSize(QSize(50, 50));
        f6PushButton_2->setMaximumSize(QSize(50, 50));
        f6PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        d2PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        d2PushButton_2->setObjectName(QString::fromUtf8("d2PushButton_2"));
        d2PushButton_2->setGeometry(QRect(810, 400, 50, 50));
        d2PushButton_2->setMinimumSize(QSize(50, 50));
        d2PushButton_2->setMaximumSize(QSize(50, 50));
        d2PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        e2PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        e2PushButton_2->setObjectName(QString::fromUtf8("e2PushButton_2"));
        e2PushButton_2->setGeometry(QRect(860, 400, 50, 50));
        e2PushButton_2->setMinimumSize(QSize(50, 50));
        e2PushButton_2->setMaximumSize(QSize(50, 50));
        e2PushButton_2->setStyleSheet(QString::fromUtf8(""));
        e5PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        e5PushButton_2->setObjectName(QString::fromUtf8("e5PushButton_2"));
        e5PushButton_2->setGeometry(QRect(860, 250, 50, 50));
        e5PushButton_2->setMinimumSize(QSize(50, 50));
        e5PushButton_2->setMaximumSize(QSize(50, 50));
        e5PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        f8PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        f8PushButton_2->setObjectName(QString::fromUtf8("f8PushButton_2"));
        f8PushButton_2->setGeometry(QRect(910, 100, 50, 50));
        f8PushButton_2->setMinimumSize(QSize(50, 50));
        f8PushButton_2->setMaximumSize(QSize(50, 50));
        f8PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        e1PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        e1PushButton_2->setObjectName(QString::fromUtf8("e1PushButton_2"));
        e1PushButton_2->setGeometry(QRect(860, 450, 50, 50));
        e1PushButton_2->setMinimumSize(QSize(50, 50));
        e1PushButton_2->setMaximumSize(QSize(50, 50));
        e1PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        e3PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        e3PushButton_2->setObjectName(QString::fromUtf8("e3PushButton_2"));
        e3PushButton_2->setGeometry(QRect(860, 350, 50, 50));
        e3PushButton_2->setMinimumSize(QSize(50, 50));
        e3PushButton_2->setMaximumSize(QSize(50, 50));
        e3PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        e8PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        e8PushButton_2->setObjectName(QString::fromUtf8("e8PushButton_2"));
        e8PushButton_2->setGeometry(QRect(860, 100, 50, 50));
        e8PushButton_2->setMinimumSize(QSize(50, 50));
        e8PushButton_2->setMaximumSize(QSize(50, 50));
        e8PushButton_2->setStyleSheet(QString::fromUtf8(""));
        d6PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        d6PushButton_2->setObjectName(QString::fromUtf8("d6PushButton_2"));
        d6PushButton_2->setGeometry(QRect(810, 200, 50, 50));
        d6PushButton_2->setMinimumSize(QSize(50, 50));
        d6PushButton_2->setMaximumSize(QSize(50, 50));
        d6PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        c1PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        c1PushButton_2->setObjectName(QString::fromUtf8("c1PushButton_2"));
        c1PushButton_2->setGeometry(QRect(760, 450, 50, 50));
        c1PushButton_2->setMinimumSize(QSize(50, 50));
        c1PushButton_2->setMaximumSize(QSize(50, 50));
        c1PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        c4PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        c4PushButton_2->setObjectName(QString::fromUtf8("c4PushButton_2"));
        c4PushButton_2->setGeometry(QRect(760, 300, 50, 50));
        c4PushButton_2->setMinimumSize(QSize(50, 50));
        c4PushButton_2->setMaximumSize(QSize(50, 50));
        c4PushButton_2->setStyleSheet(QString::fromUtf8(""));
        d1PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        d1PushButton_2->setObjectName(QString::fromUtf8("d1PushButton_2"));
        d1PushButton_2->setGeometry(QRect(810, 450, 50, 50));
        d1PushButton_2->setMinimumSize(QSize(50, 50));
        d1PushButton_2->setMaximumSize(QSize(50, 50));
        d1PushButton_2->setStyleSheet(QString::fromUtf8(""));
        d5PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        d5PushButton_2->setObjectName(QString::fromUtf8("d5PushButton_2"));
        d5PushButton_2->setGeometry(QRect(810, 250, 50, 50));
        d5PushButton_2->setMinimumSize(QSize(50, 50));
        d5PushButton_2->setMaximumSize(QSize(50, 50));
        d5PushButton_2->setStyleSheet(QString::fromUtf8(""));
        d4PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        d4PushButton_2->setObjectName(QString::fromUtf8("d4PushButton_2"));
        d4PushButton_2->setGeometry(QRect(810, 300, 50, 50));
        d4PushButton_2->setMinimumSize(QSize(50, 50));
        d4PushButton_2->setMaximumSize(QSize(50, 50));
        d4PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        f2PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        f2PushButton_2->setObjectName(QString::fromUtf8("f2PushButton_2"));
        f2PushButton_2->setGeometry(QRect(910, 400, 50, 50));
        f2PushButton_2->setMinimumSize(QSize(50, 50));
        f2PushButton_2->setMaximumSize(QSize(50, 50));
        f2PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        c6PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        c6PushButton_2->setObjectName(QString::fromUtf8("c6PushButton_2"));
        c6PushButton_2->setGeometry(QRect(760, 200, 50, 50));
        c6PushButton_2->setMinimumSize(QSize(50, 50));
        c6PushButton_2->setMaximumSize(QSize(50, 50));
        c6PushButton_2->setStyleSheet(QString::fromUtf8(""));
        d3PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        d3PushButton_2->setObjectName(QString::fromUtf8("d3PushButton_2"));
        d3PushButton_2->setGeometry(QRect(810, 350, 50, 50));
        d3PushButton_2->setMinimumSize(QSize(50, 50));
        d3PushButton_2->setMaximumSize(QSize(50, 50));
        d3PushButton_2->setStyleSheet(QString::fromUtf8(""));
        e4PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        e4PushButton_2->setObjectName(QString::fromUtf8("e4PushButton_2"));
        e4PushButton_2->setGeometry(QRect(860, 300, 50, 50));
        e4PushButton_2->setMinimumSize(QSize(50, 50));
        e4PushButton_2->setMaximumSize(QSize(50, 50));
        e4PushButton_2->setStyleSheet(QString::fromUtf8(""));
        e6PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        e6PushButton_2->setObjectName(QString::fromUtf8("e6PushButton_2"));
        e6PushButton_2->setGeometry(QRect(860, 200, 50, 50));
        e6PushButton_2->setMinimumSize(QSize(50, 50));
        e6PushButton_2->setMaximumSize(QSize(50, 50));
        e6PushButton_2->setStyleSheet(QString::fromUtf8(""));
        c2PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        c2PushButton_2->setObjectName(QString::fromUtf8("c2PushButton_2"));
        c2PushButton_2->setGeometry(QRect(760, 400, 50, 50));
        c2PushButton_2->setMinimumSize(QSize(50, 50));
        c2PushButton_2->setMaximumSize(QSize(50, 50));
        c2PushButton_2->setStyleSheet(QString::fromUtf8(""));
        g3PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        g3PushButton_2->setObjectName(QString::fromUtf8("g3PushButton_2"));
        g3PushButton_2->setGeometry(QRect(960, 350, 50, 50));
        g3PushButton_2->setMinimumSize(QSize(50, 50));
        g3PushButton_2->setMaximumSize(QSize(50, 50));
        g3PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        g7PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        g7PushButton_2->setObjectName(QString::fromUtf8("g7PushButton_2"));
        g7PushButton_2->setGeometry(QRect(960, 150, 50, 50));
        g7PushButton_2->setMinimumSize(QSize(50, 50));
        g7PushButton_2->setMaximumSize(QSize(50, 50));
        g7PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        g1PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        g1PushButton_2->setObjectName(QString::fromUtf8("g1PushButton_2"));
        g1PushButton_2->setGeometry(QRect(960, 450, 50, 50));
        g1PushButton_2->setMinimumSize(QSize(50, 50));
        g1PushButton_2->setMaximumSize(QSize(50, 50));
        g1PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        g2PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        g2PushButton_2->setObjectName(QString::fromUtf8("g2PushButton_2"));
        g2PushButton_2->setGeometry(QRect(960, 400, 50, 50));
        g2PushButton_2->setMinimumSize(QSize(50, 50));
        g2PushButton_2->setMaximumSize(QSize(50, 50));
        g2PushButton_2->setStyleSheet(QString::fromUtf8(""));
        g5PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        g5PushButton_2->setObjectName(QString::fromUtf8("g5PushButton_2"));
        g5PushButton_2->setGeometry(QRect(960, 250, 50, 50));
        g5PushButton_2->setMinimumSize(QSize(50, 50));
        g5PushButton_2->setMaximumSize(QSize(50, 50));
        g5PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        g6PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        g6PushButton_2->setObjectName(QString::fromUtf8("g6PushButton_2"));
        g6PushButton_2->setGeometry(QRect(960, 200, 50, 50));
        g6PushButton_2->setMinimumSize(QSize(50, 50));
        g6PushButton_2->setMaximumSize(QSize(50, 50));
        g6PushButton_2->setStyleSheet(QString::fromUtf8(""));
        g4PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        g4PushButton_2->setObjectName(QString::fromUtf8("g4PushButton_2"));
        g4PushButton_2->setGeometry(QRect(960, 300, 50, 50));
        g4PushButton_2->setMinimumSize(QSize(50, 50));
        g4PushButton_2->setMaximumSize(QSize(50, 50));
        g4PushButton_2->setStyleSheet(QString::fromUtf8(""));
        g8PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        g8PushButton_2->setObjectName(QString::fromUtf8("g8PushButton_2"));
        g8PushButton_2->setGeometry(QRect(960, 100, 50, 50));
        g8PushButton_2->setMinimumSize(QSize(50, 50));
        g8PushButton_2->setMaximumSize(QSize(50, 50));
        g8PushButton_2->setStyleSheet(QString::fromUtf8(""));
        h5PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        h5PushButton_2->setObjectName(QString::fromUtf8("h5PushButton_2"));
        h5PushButton_2->setGeometry(QRect(1010, 250, 50, 50));
        h5PushButton_2->setMinimumSize(QSize(50, 50));
        h5PushButton_2->setMaximumSize(QSize(50, 50));
        h5PushButton_2->setStyleSheet(QString::fromUtf8(""));
        h1PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        h1PushButton_2->setObjectName(QString::fromUtf8("h1PushButton_2"));
        h1PushButton_2->setGeometry(QRect(1010, 450, 50, 50));
        h1PushButton_2->setMinimumSize(QSize(50, 50));
        h1PushButton_2->setMaximumSize(QSize(50, 50));
        h1PushButton_2->setStyleSheet(QString::fromUtf8(""));
        h7PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        h7PushButton_2->setObjectName(QString::fromUtf8("h7PushButton_2"));
        h7PushButton_2->setGeometry(QRect(1010, 150, 50, 50));
        h7PushButton_2->setMinimumSize(QSize(50, 50));
        h7PushButton_2->setMaximumSize(QSize(50, 50));
        h7PushButton_2->setStyleSheet(QString::fromUtf8(""));
        h3PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        h3PushButton_2->setObjectName(QString::fromUtf8("h3PushButton_2"));
        h3PushButton_2->setGeometry(QRect(1010, 350, 50, 50));
        h3PushButton_2->setMinimumSize(QSize(50, 50));
        h3PushButton_2->setMaximumSize(QSize(50, 50));
        h3PushButton_2->setStyleSheet(QString::fromUtf8(""));
        h6PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        h6PushButton_2->setObjectName(QString::fromUtf8("h6PushButton_2"));
        h6PushButton_2->setGeometry(QRect(1010, 200, 50, 50));
        h6PushButton_2->setMinimumSize(QSize(50, 50));
        h6PushButton_2->setMaximumSize(QSize(50, 50));
        h6PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        h8PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        h8PushButton_2->setObjectName(QString::fromUtf8("h8PushButton_2"));
        h8PushButton_2->setGeometry(QRect(1010, 100, 50, 50));
        h8PushButton_2->setMinimumSize(QSize(50, 50));
        h8PushButton_2->setMaximumSize(QSize(50, 50));
        h8PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        h2PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        h2PushButton_2->setObjectName(QString::fromUtf8("h2PushButton_2"));
        h2PushButton_2->setGeometry(QRect(1010, 400, 50, 50));
        h2PushButton_2->setMinimumSize(QSize(50, 50));
        h2PushButton_2->setMaximumSize(QSize(50, 50));
        h2PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        h4PushButton_2 = new QPushButton(GameWithoutChatWithAlice);
        h4PushButton_2->setObjectName(QString::fromUtf8("h4PushButton_2"));
        h4PushButton_2->setGeometry(QRect(1010, 300, 50, 50));
        h4PushButton_2->setMinimumSize(QSize(50, 50));
        h4PushButton_2->setMaximumSize(QSize(50, 50));
        h4PushButton_2->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        boardView->raise();
        imageLabel->raise();
        formLayoutWidget_3->raise();
        verticalLayoutWidget->raise();
        verticalLayoutWidget_2->raise();
        formLayoutWidget_5->raise();
        boardView2->raise();
        c4PushButton->raise();
        graphicsView->raise();
        b5PushButton->raise();
        f2PushButton->raise();
        b3PushButton->raise();
        g2PushButton->raise();
        b6PushButton->raise();
        h3PushButton->raise();
        a3PushButton->raise();
        d7PushButton->raise();
        a7PushButton->raise();
        f6PushButton->raise();
        h7PushButton->raise();
        b1PushButton->raise();
        d8PushButton->raise();
        e3PushButton->raise();
        e6PushButton->raise();
        c2PushButton->raise();
        h8PushButton->raise();
        a6PushButton->raise();
        d5PushButton->raise();
        d4PushButton->raise();
        c3PushButton->raise();
        b7PushButton->raise();
        c7PushButton->raise();
        e7PushButton->raise();
        d1PushButton->raise();
        a5PushButton->raise();
        a8PushButton->raise();
        c5PushButton->raise();
        g8PushButton->raise();
        g1PushButton->raise();
        f1PushButton->raise();
        e2PushButton->raise();
        f8PushButton->raise();
        f7PushButton->raise();
        b8PushButton->raise();
        h5PushButton->raise();
        a2PushButton->raise();
        d2PushButton->raise();
        e1PushButton->raise();
        g3PushButton->raise();
        f3PushButton->raise();
        a1PushButton->raise();
        d6PushButton->raise();
        d3PushButton->raise();
        h6PushButton->raise();
        b2PushButton->raise();
        f4PushButton->raise();
        g6PushButton->raise();
        c6PushButton->raise();
        g4PushButton->raise();
        h4PushButton->raise();
        a4PushButton->raise();
        g5PushButton->raise();
        c8PushButton->raise();
        b4PushButton->raise();
        h1PushButton->raise();
        e5PushButton->raise();
        c1PushButton->raise();
        e8PushButton->raise();
        e4PushButton->raise();
        f5PushButton->raise();
        h2PushButton->raise();
        g7PushButton->raise();
        b5PushButton_2->raise();
        b6PushButton_2->raise();
        a4PushButton_2->raise();
        a6PushButton_2->raise();
        a8PushButton_2->raise();
        b4PushButton_2->raise();
        b8PushButton_2->raise();
        b2PushButton_2->raise();
        b7PushButton_2->raise();
        a2PushButton_2->raise();
        a5PushButton_2->raise();
        a3PushButton_2->raise();
        a7PushButton_2->raise();
        a1PushButton_2->raise();
        b1PushButton_2->raise();
        b3PushButton_2->raise();
        f1PushButton_2->raise();
        d8PushButton_2->raise();
        f3PushButton_2->raise();
        f7PushButton_2->raise();
        c8PushButton_2->raise();
        f5PushButton_2->raise();
        c7PushButton_2->raise();
        f4PushButton_2->raise();
        c3PushButton_2->raise();
        d7PushButton_2->raise();
        e7PushButton_2->raise();
        c5PushButton_2->raise();
        f6PushButton_2->raise();
        d2PushButton_2->raise();
        e2PushButton_2->raise();
        e5PushButton_2->raise();
        f8PushButton_2->raise();
        e1PushButton_2->raise();
        e3PushButton_2->raise();
        e8PushButton_2->raise();
        d6PushButton_2->raise();
        c1PushButton_2->raise();
        c4PushButton_2->raise();
        d1PushButton_2->raise();
        d5PushButton_2->raise();
        d4PushButton_2->raise();
        f2PushButton_2->raise();
        c6PushButton_2->raise();
        d3PushButton_2->raise();
        e4PushButton_2->raise();
        e6PushButton_2->raise();
        c2PushButton_2->raise();
        g3PushButton_2->raise();
        g7PushButton_2->raise();
        g1PushButton_2->raise();
        g2PushButton_2->raise();
        g5PushButton_2->raise();
        g6PushButton_2->raise();
        g4PushButton_2->raise();
        g8PushButton_2->raise();
        h5PushButton_2->raise();
        h1PushButton_2->raise();
        h7PushButton_2->raise();
        h3PushButton_2->raise();
        h6PushButton_2->raise();
        h8PushButton_2->raise();
        h2PushButton_2->raise();
        h4PushButton_2->raise();

        retranslateUi(GameWithoutChatWithAlice);

        QMetaObject::connectSlotsByName(GameWithoutChatWithAlice);
    } // setupUi

    void retranslateUi(QDialog *GameWithoutChatWithAlice)
    {
        GameWithoutChatWithAlice->setWindowTitle(QApplication::translate("GameWithoutChatWithAlice", "Alice Chess", nullptr));
        imageLabel->setText(QString());
        takenLabel->setText(QApplication::translate("GameWithoutChatWithAlice", "TAKEN :", nullptr));
        chgTakenLabel->setText(QApplication::translate("GameWithoutChatWithAlice", "PQBR", nullptr));
        modeLabel->setText(QApplication::translate("GameWithoutChatWithAlice", "<html><head/><body><p>MODE:</p></body></html>", nullptr));
        chgModelabel->setText(QApplication::translate("GameWithoutChatWithAlice", "mode", nullptr));
        colourLabel->setText(QApplication::translate("GameWithoutChatWithAlice", "<html><head/><body><p>COLOUR:</p></body></html>", nullptr));
        chgColourLabel->setText(QApplication::translate("GameWithoutChatWithAlice", "colour", nullptr));
        lastMoveLabel->setText(QApplication::translate("GameWithoutChatWithAlice", "LAST MOVE:", nullptr));
        chgLastMovelabel->setText(QApplication::translate("GameWithoutChatWithAlice", "last move", nullptr));
        opponentNameLabel->setText(QApplication::translate("GameWithoutChatWithAlice", "OPPONENT NAME:", nullptr));
        chgOpponentNamelabel->setText(QApplication::translate("GameWithoutChatWithAlice", "opponent", nullptr));
        surrendButton->setText(QApplication::translate("GameWithoutChatWithAlice", "Surrend", nullptr));
        timeLabel->setText(QApplication::translate("GameWithoutChatWithAlice", "Time:", nullptr));
        chgTimeLabel->setText(QApplication::translate("GameWithoutChatWithAlice", "0:00", nullptr));
        checkUpdatelabel->setText(QApplication::translate("GameWithoutChatWithAlice", "TURN:", nullptr));
        turnLabel->setText(QApplication::translate("GameWithoutChatWithAlice", "Black", nullptr));
        takenEnnemyLabel->setText(QApplication::translate("GameWithoutChatWithAlice", "TAKEN :", nullptr));
        chgTakenEnnemyLabel->setText(QApplication::translate("GameWithoutChatWithAlice", "PQBR", nullptr));
        h3PushButton->setText(QString());
        e4PushButton->setText(QString());
        b5PushButton->setText(QString());
        e1PushButton->setText(QString());
        c3PushButton->setText(QString());
        b3PushButton->setText(QString());
        d7PushButton->setText(QString());
        f7PushButton->setText(QString());
        h7PushButton->setText(QString());
        d4PushButton->setText(QString());
        e5PushButton->setText(QString());
        e8PushButton->setText(QString());
        g8PushButton->setText(QString());
        b7PushButton->setText(QString());
        a4PushButton->setText(QString());
        g4PushButton->setText(QString());
        a1PushButton->setText(QString());
        a6PushButton->setText(QString());
        g7PushButton->setText(QString());
        c7PushButton->setText(QString());
        h8PushButton->setText(QString());
        g5PushButton->setText(QString());
        b4PushButton->setText(QString());
        f6PushButton->setText(QString());
        g2PushButton->setText(QString());
        g1PushButton->setText(QString());
        h4PushButton->setText(QString());
        d3PushButton->setText(QString());
        a3PushButton->setText(QString());
        a7PushButton->setText(QString());
        h1PushButton->setText(QString());
        h6PushButton->setText(QString());
        f2PushButton->setText(QString());
        d6PushButton->setText(QString());
        f1PushButton->setText(QString());
        f4PushButton->setText(QString());
        e6PushButton->setText(QString());
        d5PushButton->setText(QString());
        a8PushButton->setText(QString());
        c1PushButton->setText(QString());
        g3PushButton->setText(QString());
        d2PushButton->setText(QString());
        d8PushButton->setText(QString());
        f5PushButton->setText(QString());
        f8PushButton->setText(QString());
        g6PushButton->setText(QString());
        f3PushButton->setText(QString());
        e3PushButton->setText(QString());
        b6PushButton->setText(QString());
        c8PushButton->setText(QString());
        e2PushButton->setText(QString());
        h2PushButton->setText(QString());
        h5PushButton->setText(QString());
        a2PushButton->setText(QString());
        b8PushButton->setText(QString());
        c4PushButton->setText(QString());
        c5PushButton->setText(QString());
        b2PushButton->setText(QString());
        c2PushButton->setText(QString());
        c6PushButton->setText(QString());
        e7PushButton->setText(QString());
        d1PushButton->setText(QString());
        b1PushButton->setText(QString());
        a5PushButton->setText(QString());
        b5PushButton_2->setText(QString());
        b6PushButton_2->setText(QString());
        a4PushButton_2->setText(QString());
        a6PushButton_2->setText(QString());
        a8PushButton_2->setText(QString());
        b4PushButton_2->setText(QString());
        b8PushButton_2->setText(QString());
        b2PushButton_2->setText(QString());
        b7PushButton_2->setText(QString());
        a2PushButton_2->setText(QString());
        a5PushButton_2->setText(QString());
        a3PushButton_2->setText(QString());
        a7PushButton_2->setText(QString());
        a1PushButton_2->setText(QString());
        b1PushButton_2->setText(QString());
        b3PushButton_2->setText(QString());
        f1PushButton_2->setText(QString());
        d8PushButton_2->setText(QString());
        f3PushButton_2->setText(QString());
        f7PushButton_2->setText(QString());
        c8PushButton_2->setText(QString());
        f5PushButton_2->setText(QString());
        c7PushButton_2->setText(QString());
        f4PushButton_2->setText(QString());
        c3PushButton_2->setText(QString());
        d7PushButton_2->setText(QString());
        e7PushButton_2->setText(QString());
        c5PushButton_2->setText(QString());
        f6PushButton_2->setText(QString());
        d2PushButton_2->setText(QString());
        e2PushButton_2->setText(QString());
        e5PushButton_2->setText(QString());
        f8PushButton_2->setText(QString());
        e1PushButton_2->setText(QString());
        e3PushButton_2->setText(QString());
        e8PushButton_2->setText(QString());
        d6PushButton_2->setText(QString());
        c1PushButton_2->setText(QString());
        c4PushButton_2->setText(QString());
        d1PushButton_2->setText(QString());
        d5PushButton_2->setText(QString());
        d4PushButton_2->setText(QString());
        f2PushButton_2->setText(QString());
        c6PushButton_2->setText(QString());
        d3PushButton_2->setText(QString());
        e4PushButton_2->setText(QString());
        e6PushButton_2->setText(QString());
        c2PushButton_2->setText(QString());
        g3PushButton_2->setText(QString());
        g7PushButton_2->setText(QString());
        g1PushButton_2->setText(QString());
        g2PushButton_2->setText(QString());
        g5PushButton_2->setText(QString());
        g6PushButton_2->setText(QString());
        g4PushButton_2->setText(QString());
        g8PushButton_2->setText(QString());
        h5PushButton_2->setText(QString());
        h1PushButton_2->setText(QString());
        h7PushButton_2->setText(QString());
        h3PushButton_2->setText(QString());
        h6PushButton_2->setText(QString());
        h8PushButton_2->setText(QString());
        h2PushButton_2->setText(QString());
        h4PushButton_2->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class GameWithoutChatWithAlice: public Ui_GameWithoutChatWithAlice {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_GAMEWITHOUTCHATWITHALICE_H
